### ISSUE TITLE
Usage and Searching Content

### ISSUE THREAD

**Issue by emaildano** [dinhtungdu/command-palette#6]
Hey! I love this plugin. I'm eager to use it on all my sites. I'm curious about a couple things.

1. Can I search posts or pages?
2. Do you have any documentation on how extend what it searches?

I would like to contribute. The issue I'm having using the plugin is searching specific post titles within a custom post type and the default posts. They individual posts are not available in the search.

If you can show me how to add this if it's not a feature I'd be happy to add them and submit a PR.

**Comment by dinhtungdu** [comment]
First, I'm sorry for the super late reply :(.

1. You can. I thought about posts and pages search too but I could find any time to implement them.
2. Right now I don't have any documentation on extending the search. But let's create one now!

We group items by sources. So to extend the search, we can add new Source by extending the `Base` abstract class. Take the `Custom` source as the inspiration. The limitation of the current approach is we need to add all items before we can search for it. The search here is just a fuzzy search to filter the correct items. That means the solution works in theory but the performance will be 🤦‍♂️.

To be honest, the current source design does not scale. I will need to add ajax support to the source before you can extend it and post search. I want we can add ajax search without touching JS, just extend the class in PHP and we'll have ajax working. I will update you when it's available.

Again, so sorry for the late reply. Github notification sucks but it's my mistake 🤦‍♂️.

**Comment by emaildano** [comment]
Great, thanks! No worries on the late reply. Open source projects are a lot of time so I completely understand.

I'll close this out for now. If you do add support for searching CPTs, posts pages, etc. that would be super amazing.
